# command: "C:\\Windows\\System32\\cmd.exe"
command: "/mnt/c/Windows/System32/cmd.exe"
# command: "cmd"
auto_shutdown: true
services:
  - name: "my-app.bat"
    # windows path
    path: "C:\\Users\\user\\Documents\\service-jar"
    # linux path
    # path: "/mnt/c/Users/user/Documents/service-jar"
    skip: false
    args: 
  - name: "simple-loop2.jar"
    path: "/home/user/java"
    skip: true
    args: 
      - "-jar"
      - "/home/user/java/simple-loop2.jar"
